-- public.bc_property definition

-- steepslope -- steepslope -- steepslope -- steepslope -- steepslope -- steepslope -- steepslope -- steepslope

-- DROP TABLE public.bc_property;

CREATE TABLE public.bc_property (
	objectid int4 NOT NULL,
	pinnum varchar(50) NULL,
	pin varchar(15) NULL,
	pinext varchar(50) NULL,
	"owner" varchar(50) NULL,
	nmptype varchar(150) NULL,
	taxyear varchar(50) NULL,
	condounit varchar(50) NULL,
	condobuilding varchar(50) NULL,
	deedbook varchar(50) NULL,
	deedpage varchar(50) NULL,
	platbook varchar(50) NULL,
	platpage varchar(50) NULL,
	subname varchar(50) NULL,
	sublot varchar(50) NULL,
	subblock varchar(50) NULL,
	subsect varchar(50) NULL,
	updatedate varchar(50) NULL,
	housenumber varchar(50) NULL,
	numbersuffix varchar(50) NULL,
	direction varchar(50) NULL,
	streetname varchar(50) NULL,
	streettype varchar(50) NULL,
	township varchar(50) NULL,
	acreage numeric(38,8) NULL,
	accountnumber varchar(50) NULL,
	deeddate varchar(50) NULL,
	stamps numeric(38,8) NULL,
	instrument varchar(50) NULL,
	reason varchar(50) NULL,
	county varchar(50) NULL,
	city varchar(50) NULL,
	firedistrict varchar(50) NULL,
	schooldistrict varchar(50) NULL,
	careof varchar(50) NULL,
	address varchar(50) NULL,
	cityname varchar(50) NULL,
	state varchar(50) NULL,
	zipcode varchar(50) NULL,
	"class" varchar(50) NULL,
	improved varchar(50) NULL,
	exempt varchar(50) NULL,
	priced varchar(50) NULL,
	totalmarketvalue numeric(38,8) NULL,
	appraisedvalue numeric(38,8) NULL,
	taxvalue numeric(38,8) NULL,
	landuse varchar(50) NULL,
	neighborhoodcode varchar(50) NULL,
	landvalue numeric(38,8) NULL,
	buildingvalue numeric(38,8) NULL,
	improvementvalue numeric(38,8) NULL,
	appraisalarea varchar(50) NULL,
	state_route varchar(50) NULL,
	state_route_suffix varchar(50) NULL,
	propcard varchar(150) NULL,
	oldpinnum varchar(50) NULL,
	citystatezip varchar(50) NULL,
	deedurl varchar(254) NULL,
	platurl varchar(254) NULL,
	shape geometry(MULTIPOLYGON, 2264) NULL,
	CONSTRAINT bc_property_pkey PRIMARY KEY (objectid)
);
grant select on public.bc_property to steepslopeapp;
CREATE INDEX bc_property_shape_1467142390314 ON public.bc_property USING gist (shape);


-- mdastore 
-- DROP TABLE public.bc_property;

CREATE TABLE public.bc_property (
	objectid int4 NOT NULL,
	pinnum varchar(50) NULL,
	pin varchar(15) NULL,
	pinext varchar(50) NULL,
	"owner" varchar(50) NULL,
	nmptype varchar(150) NULL,
	taxyear varchar(50) NULL,
	condounit varchar(50) NULL,
	condobuilding varchar(50) NULL,
	deedbook varchar(50) NULL,
	deedpage varchar(50) NULL,
	platbook varchar(50) NULL,
	platpage varchar(50) NULL,
	subname varchar(50) NULL,
	sublot varchar(50) NULL,
	subblock varchar(50) NULL,
	subsect varchar(50) NULL,
	updatedate varchar(50) NULL,
	housenumber varchar(50) NULL,
	numbersuffix varchar(50) NULL,
	direction varchar(50) NULL,
	streetname varchar(50) NULL,
	streettype varchar(50) NULL,
	township varchar(50) NULL,
	acreage numeric(38,8) NULL,
	accountnumber varchar(50) NULL,
	deeddate varchar(50) NULL,
	stamps numeric(38,8) NULL,
	instrument varchar(50) NULL,
	reason varchar(50) NULL,
	county varchar(50) NULL,
	city varchar(50) NULL,
	firedistrict varchar(50) NULL,
	schooldistrict varchar(50) NULL,
	careof varchar(50) NULL,
	address varchar(50) NULL,
	cityname varchar(50) NULL,
	state varchar(50) NULL,
	zipcode varchar(50) NULL,
	"class" varchar(50) NULL,
	improved varchar(50) NULL,
	exempt varchar(50) NULL,
	priced varchar(50) NULL,
	totalmarketvalue numeric(38,8) NULL,
	appraisedvalue numeric(38,8) NULL,
	taxvalue numeric(38,8) NULL,
	landuse varchar(50) NULL,
	neighborhoodcode varchar(50) NULL,
	landvalue numeric(38,8) NULL,
	buildingvalue numeric(38,8) NULL,
	improvementvalue numeric(38,8) NULL,
	appraisalarea varchar(50) NULL,
	state_route varchar(50) NULL,
	state_route_suffix varchar(50) NULL,
	propcard varchar(150) NULL,
	oldpinnum varchar(50) NULL,
	citystatezip varchar(50) NULL,
	shape geometry(MULTIPOLYGON, 2264) NULL,
	deedurl varchar(254) NULL,
	platurl varchar(254) NULL,
	CONSTRAINT pk_bc_property PRIMARY KEY (objectid)
);
CREATE INDEX a36_ix1 ON public.bc_property USING gist (shape);
create index bc_property_pinnum on public.bc_property using pinnum;
